[env]
platform = atmelavr
board = nanoatmega328new
build_flags = -Wl,-u,vfprintf -lprintf_flt -lm -Wl,-u,vfscanf -lscanf_flt -lm
monitor_echo = yes

[env:sensor_test]
build_src_filter = +<sensor_test/*>

[env:leg_test]
build_src_filter = +<leg_test/*>

[env:comms_test]
build_src_filter = +<comms_test/*>

[env:robot]
build_src_filter = +<robot/*>
